#' Generic plot function for crossnma.model object.
#'
#' @param x The object generated by the crossnma.run function.
#'
#' @param ... \dots
#'
#' @export
#'
plot.crossnma <- function(x, ...)
{
  plot(x$samples, ...)
}
