#' Trace plot of MCMC outputs.
#' @description Produces a separate plot for each parameter in the model. Each plot shows iterations vs sampled values. It takes crossnma.run object.
#' @param x The object generated by the crossnma.run function.
#'
#' @param ... \dots
#'
#' @export
#'
plot.crossnma <- function(x, ...)
{
  plot(x$samples, ...)
}
